CREATE TABLE IF NOT EXISTS entries (
  id CHAR(36) PRIMARY KEY,
  text TEXT NOT NULL,
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  mood VARCHAR(50)
);